
POST http://localhost:8080/api/v1/user/register HTTP/1.1
Content-Type: application/json

{
  "fname":"Dhruv",
  "lname":"Kapoor",
  "email":"dk@gmail.com",
  "password":"password"
}

###

POST http://localhost:8080/api/v1/user/login HTTP/1.1
Content-Type: application/json

{
  "email":"dk@gmail.com",
  "password":"password"
}



###

# Apply for doctor

POST http://localhost:8080/api/v1/user/apply-doctor HTTP/1.1
Content-Type: application/json

{
  "userId": "67425d000089059063691b72",
  "fname": "Dhruv",
  "lname": "Kapoor",
  "email": "dk@gmail.com",
  "phone": "6382476404",
  "website": "www.google.com",
  "address": "abc, def",
  "specialization": "Neurology",
  "experience": "7 Years",
  "feesPerConsultation": 500,
  "timings": "2024-03-25T00:00:00.000Z"
}

###

# Get all doctors

GET http://localhost:8080/api/v1/user/getAllDoctors HTTP/1.1

### 

# Book a doctor (without auth)

POST http://localhost:8080/api/v1/user/book-2 HTTP/1.1
Content-Type: application/json

{
  "userId" : "674942858d7a6688484156c5",
  "doctorId" : "67425d000089059063691b72"
}

### Get Doctor Appointments

POST http://localhost:8080/api/v1/user/user-appointments HTTP/1.1
Content-Type: application/json

{
  "userId": "674942858d7a6688484156c5"
}

### GET ALL PATIENTS

GET http://localhost:8080/api/v1/admin/getAllUsers HTTP/1.1


### Approve Doctor
POST http://localhost:8080/api/v1/admin/approveDoctor HTTP/1.1
Content-Type: application/json

{
  "userId" : "674942858d7a6688484156c5"
}

###


### Get Doctor Appointments
GET http://localhost:8080/api/v1/doctor/doctor-appointments/675e9b7b93c28e032a17c28e HTTP/1.1